name: ecentialsclone
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.13
  animated_splash_screen: ^1.2.0
  get: ^4.6.1
  smooth_page_indicator: ^1.0.0+2
  flutter_neumorphic: ^3.2.0
  curved_navigation_bar: ^1.0.3
  dotted_border: ^2.0.0+2
  intl: ^0.17.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  fonts: 
  - family: Montserrat
    fonts: 
    - asset: assets/fonts/Montserrat-Regular.ttf
  - family: EcentialsIcons
    fonts: 
    - asset: assets/fonts/EcentialsIcons.ttf

# Images route
  assets:
    - assets/images/